// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Protosweeper.Web.Data;

#nullable disable

namespace Protosweeper.Web.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260418221123_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Protosweeper.Web.Models.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialY")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Seed")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
